/*
 * Generated by erpcgen 1.13.0 on Wed Mar 26 05:10:01 2025.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_c_remote_display_client_h_)
#define _c_remote_display_client_h_

#include "remote_display_common.h"
#include "erpc_client_manager.h"

#if defined(__cplusplus)
extern "C"
{
#endif

#if !defined(ERPC_FUNCTIONS_DEFINITIONS)
#define ERPC_FUNCTIONS_DEFINITIONS


/*! @brief DisplayInterface identifiers */
enum _DisplayInterface_ids
{
    kDisplayInterface_service_id = 1,
    kDisplayInterface_sendDisplayCommand_id = 1,
};

//! @name DisplayInterface
//@{
void sendDisplayCommand(const Command * cmd);
//@}

#endif // ERPC_FUNCTIONS_DEFINITIONS

void initDisplayInterface_client(erpc_client_t client);

void deinitDisplayInterface_client(void);

#if defined(__cplusplus)
}
#endif

#endif // _c_remote_display_client_h_
