/*
 * Generated by erpcgen 1.13.0 on Wed Mar 26 05:10:01 2025.
 *
 * AUTOGENERATED - DO NOT EDIT
 */

#if !defined(_c_remote_display_server_h_)
#define _c_remote_display_server_h_

#include "remote_display_common.h"

#if defined(__cplusplus)
extern "C" {
#endif

typedef void *erpc_service_t;

#if !defined(ERPC_FUNCTIONS_DEFINITIONS)
#define ERPC_FUNCTIONS_DEFINITIONS

/*! @brief DisplayInterface identifiers */
enum _DisplayInterface_ids {
  kDisplayInterface_service_id = 1,
  kDisplayInterface_sendDisplayCommand_id = 1,
};

//! @name DisplayInterface
//@{
void sendDisplayCommand(const Command *cmd);
//@}

#endif // ERPC_FUNCTIONS_DEFINITIONS

/*! @brief Return DisplayInterface_service service item. */
erpc_service_t create_DisplayInterface_service(void);

/*! @brief Destroy DisplayInterface_service service item. */
void destroy_DisplayInterface_service(erpc_service_t service);

#if defined(__cplusplus)
}
#endif

#endif // _c_remote_display_server_h_
