/*
 * Generated by erpcgen 1.13.0 on Wed Mar 26 05:10:01 2025.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#include <new>
#include "c_remote_display_server.h"
#include "remote_display_server.hpp"
#include "erpc_manually_constructed.hpp"

using namespace erpc;
using namespace std;
using namespace erpcShim;


class DisplayInterface_server: public DisplayInterface_interface
{
    public:
        virtual ~DisplayInterface_server() {};


        void sendDisplayCommand(const Command * cmd)
        {
            ::sendDisplayCommand(cmd);
        }
};

ERPC_MANUALLY_CONSTRUCTED_STATIC(DisplayInterface_service, s_DisplayInterface_service);
ERPC_MANUALLY_CONSTRUCTED_STATIC(DisplayInterface_server, s_DisplayInterface_server);

erpc_service_t create_DisplayInterface_service(void)
{
    erpc_service_t service;

#if ERPC_ALLOCATION_POLICY == ERPC_ALLOCATION_POLICY_DYNAMIC
    service = new (nothrow) DisplayInterface_service(new (nothrow)DisplayInterface_server());
#else
    if (s_DisplayInterface_service.isUsed())
    {
        service = NULL;
    }
    else
    {
        s_DisplayInterface_server.construct();
        s_DisplayInterface_service.construct(s_DisplayInterface_server.get());
        service = s_DisplayInterface_service.get();
    }
#endif

    return service;
}

void destroy_DisplayInterface_service(erpc_service_t service)
{
#if ERPC_ALLOCATION_POLICY == ERPC_ALLOCATION_POLICY_DYNAMIC
    if (service)
    {
        delete (DisplayInterface_server *)(((DisplayInterface_service *)service)->getHandler());
        delete (DisplayInterface_service *)service;
    }
#else
    (void)service;
    erpc_assert(service == s_DisplayInterface_service.get());
    s_DisplayInterface_service.destroy();
    s_DisplayInterface_server.destroy();
#endif
}

