/*
 * Generated by erpcgen 1.13.0 on Wed Mar 26 05:10:01 2025.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#include "c_remote_display_client.h"
#include "remote_display_client.hpp"
#include "erpc_manually_constructed.hpp"

using namespace erpc;
using namespace std;
using namespace erpcShim;


#if ERPC_ALLOCATION_POLICY == ERPC_ALLOCATION_POLICY_DYNAMIC
DisplayInterface_client *s_DisplayInterface_client = nullptr;
#else
ERPC_MANUALLY_CONSTRUCTED_STATIC(DisplayInterface_client, s_DisplayInterface_client);
#endif

void sendDisplayCommand(const Command * cmd)
{
    s_DisplayInterface_client->sendDisplayCommand(cmd);
}

void initDisplayInterface_client(erpc_client_t client)
{
#if ERPC_ALLOCATION_POLICY == ERPC_ALLOCATION_POLICY_DYNAMIC
    erpc_assert(s_DisplayInterface_client == nullptr);
    s_DisplayInterface_client = new DisplayInterface_client(reinterpret_cast<ClientManager *>(client));
#else
    erpc_assert(!s_DisplayInterface_client.isUsed());
    s_DisplayInterface_client.construct(reinterpret_cast<ClientManager *>(client));
#endif
}

void deinitDisplayInterface_client(void)
{
#if ERPC_ALLOCATION_POLICY == ERPC_ALLOCATION_POLICY_DYNAMIC
    if (s_DisplayInterface_client != nullptr)
    {
        delete s_DisplayInterface_client;
        s_DisplayInterface_client = nullptr;
    }
#else
    s_DisplayInterface_client.destroy();
#endif
}
