/*
 * Generated by erpcgen 1.13.0 on Wed Mar 26 05:10:01 2025.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_remote_display_common_hpp_)
#define _remote_display_common_hpp_


#include <cstddef>
#include <cstdint>

#include "erpc_version.h"

#if 11300 != ERPC_VERSION_NUMBER
#error "The generated shim code version is different to the rest of eRPC code."
#endif


#if !defined(ERPC_TYPE_DEFINITIONS_ERPCSHIM)
#define ERPC_TYPE_DEFINITIONS_ERPCSHIM

// Aliases data types declarations
typedef struct Command Command;

// Structures/unions data types declarations
struct Command
{
    Context context;
    uint16_t data;
};


#endif // ERPC_TYPE_DEFINITIONS_ERPCSHIM


#endif // _remote_display_common_hpp_
