/*
 * Generated by erpcgen 1.13.0 on Wed Mar 26 05:10:01 2025.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_remote_display_client_hpp_)
#define _remote_display_client_hpp_

#include "remote_display_interface.hpp"

#include "erpc_client_manager.h"

namespace erpcShim
{

class DisplayInterface_client: public DisplayInterface_interface
{
    public:
        DisplayInterface_client(erpc::ClientManager *manager);

        virtual ~DisplayInterface_client();

        virtual void sendDisplayCommand(const Command * cmd);

    protected:
        erpc::ClientManager *m_clientManager;
};

} // erpcShim


#endif // _remote_display_client_hpp_
