/*
 * Generated by erpcgen 1.13.0 on Wed Mar 26 05:10:01 2025.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_remote_display_interface_hpp_)
#define _remote_display_interface_hpp_

#include "remote_display_common.hpp"

namespace erpcShim
{


// Abstract base class for DisplayInterface
class DisplayInterface_interface
{
    public:
        static const uint8_t m_serviceId = 1;
        static const uint8_t m_sendDisplayCommandId = 1;

        virtual ~DisplayInterface_interface(void);

        virtual void sendDisplayCommand(const Command * cmd) = 0;
private:
};
} // erpcShim


#endif // _remote_display_interface_hpp_
