/*
 * Generated by erpcgen 1.13.0 on Wed Mar 26 05:10:01 2025.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_remote_display_server_hpp_)
#define _remote_display_server_hpp_

#include "remote_display_interface.hpp"

#include "erpc_server.hpp"
#include "erpc_codec.hpp"

#if 11300 != ERPC_VERSION_NUMBER
#error "The generated shim code version is different to the rest of eRPC code."
#endif


namespace erpcShim
{

/*!
 * @brief Service subclass for DisplayInterface.
 */
class DisplayInterface_service : public erpc::Service
{
public:
    DisplayInterface_service(DisplayInterface_interface *_DisplayInterface_interface);

    virtual ~DisplayInterface_service();

    /*! @brief return service interface handler. */
    DisplayInterface_interface* getHandler(void);

    /*! @brief Call the correct server shim based on method unique ID. */
    virtual erpc_status_t handleInvocation(uint32_t methodId, uint32_t sequence, erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory, erpc::Transport * transport);

private:
    DisplayInterface_interface *m_handler;
    /*! @brief Server shim for sendDisplayCommand of DisplayInterface interface. */
    erpc_status_t sendDisplayCommand_shim(erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory, erpc::Transport * transport, uint32_t sequence);
};

} // erpcShim


#endif // _remote_display_server_hpp_
