/*
 * Generated by erpcgen 1.13.0 on Wed Mar 26 05:10:01 2025.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#include "remote_display_interface.hpp"

#if 11300 != ERPC_VERSION_NUMBER
#error "The generated shim code version is different to the rest of eRPC code."
#endif


using namespace std;
using namespace erpcShim;

DisplayInterface_interface::~DisplayInterface_interface(void)
{
}
